version: "3.9"
services:
  api:
    build:
      context: ./api
    volumes:
      - static_volume:/app/static
    command: sh -c "python manage.py collectstatic --no-input && gunicorn parsing_uzt_2.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/var/www/html/static
    ports:
      - "80:80"
    depends_on:
      - api
  telebot:
    build:
      context: ./telebot
    depends_on:
      - api
  webscraper:
    build:
      context: ./webscraper
    depends_on:
      - api
  sendler:
    build:
      context: ./sendler
    depends_on:
      - api
volumes:
  static_volume:
