# Generated by Django 4.2 on 2023-04-28 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_job_date_upd"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category_of_job",
            new_name="CategoryOfJob",
        ),
        migrations.RenameModel(
            old_name="Tg_User",
            new_name="TgUser",
        ),
    ]
