# Generated by Django 4.2 on 2023-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_category_of_job_categoryofjob_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryofjob',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='categoryofjob',
            name='last_id',
            field=models.IntegerField(null=True),
        ),
    ]
