# Generated by Django 4.2 on 2023-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_categoryofjob_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryofjob',
            name='event_target',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('category', 'url')},
        ),
    ]
