# Generated by Django 4.2 on 2023-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categoryofjob_event_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='subscriptions',
            field=models.TextField(blank=True),
        ),
    ]
