# Generated by Django 4.2 on 2023-04-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tguser_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='subscriptions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
