# Generated by Django 4.2 on 2023-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tguser_subscriptions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('category', 'url'), name='category_url'),
        ),
    ]
