# Generated by Django 4.2 on 2023-05-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_subscriber_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
