# Generated by Django 4.2 on 2023-05-04 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_alter_subscriber_telegram_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"], "verbose_name": "Category"},
        ),
    ]
