# Generated by Django 4.2 on 2023-05-05 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_subscriber_options_remove_subscriber_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
