# Generated by Django 4.2 on 2023-05-05 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_subscriber_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriber",
            old_name="subscribed_to",
            new_name="data",
        ),
    ]
