# Generated by Django 4.2 on 2023-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_to',
            field=models.ManyToManyField(through='api.Subscription', to='api.category'),
        ),
    ]
