# Generated by Django 4.2 on 2023-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('category', 'subscriber'), name='user_and_category'),
        ),
    ]
