# Generated by Django 4.2 on 2023-04-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Tg_User',
        ),
        migrations.RenameField(
            model_name='tg_user',
            old_name='user_tg_id',
            new_name='telegram_id',
        ),
    ]
