# Generated by Django 4.2 on 2023-05-13 19:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscriber_subscribed_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last_upd_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='last_upd_id',
        ),
        migrations.AddField(
            model_name='job',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_last_sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 19, 3, 38, 336279, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
