# Generated by Django 4.2 on 2023-04-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_tg_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tg_user',
            old_name='subscribes',
            new_name='subscriptions',
        ),
    ]
