# Generated by Django 4.2 on 2023-04-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_subscribes_tg_user_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_of_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_target', models.CharField(max_length=255)),
                ('last_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upd', models.DateField()),
                ('name', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('place', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category_of_job')),
            ],
        ),
    ]
