# Generated by Django 4.2 on 2023-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_subscription_user_and_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscriptions', through='api.Subscription', to='api.category'),
        ),
    ]
