# Generated by Django 4.2 on 2023-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_of_job_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_upd',
            field=models.DateField(auto_now_add=True),
        ),
    ]
