# Generated by Django 4.2 on 2023-05-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subscriber_subscribed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_to',
            field=models.ManyToManyField(through='api.Subscription', to='api.category'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.subscriber'),
        ),
    ]
