# Generated by Django 4.2 on 2023-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_last_sent',
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', max_length=60),
        ),
    ]
