# Generated by Django 4.2 on 2023-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_subscription_date_last_sent_alter_token_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSuccessfulSendDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
