# Generated by Django 4.2 on 2023-05-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_categoryofjob_options_alter_job_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryOfJob',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='TgUser',
            new_name='Subscribers',
        ),
        migrations.RenameField(
            model_name='subscribers',
            old_name='subscriptions',
            new_name='subscribed_to',
        ),
    ]
