# Generated by Django 4.2 on 2023-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
